#!/usr/bin/env python3
"""Generate the QML type description for the Python-side singleton.

QML tooling (``qmllint``, IDE completion, the QML compiler) can only reason
about types it has a description for. Without this file every reference to the
controller is reported as an unqualified access and nothing about it can be
type-checked.

The description is generated from the live ``QMetaObject`` rather than written
by hand, so it cannot drift from the implementation. Regenerate it whenever a
property, signal or slot on :class:`~javris.controller.HudController` changes,
and commit the result:

    python tools/generate_qmltypes.py
"""

from __future__ import annotations

import sys
from pathlib import Path

from PySide6.QtCore import QMetaMethod, QMetaProperty, QMetaType

SRC_ROOT = Path(__file__).resolve().parents[1] / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from javris.controller import HudController  # noqa: E402
from javris.qmlregistration import (  # noqa: E402
    CONTROLLER_TYPE,
    QML_MAJOR_VERSION,
    QML_MINOR_VERSION,
    QML_MODULE,
)

OUTPUT = SRC_ROOT / "javris" / "core" / f"{QML_MODULE}.qmltypes"

#: Qt metatype names that QML tooling expects under a different spelling.
_TYPE_ALIASES = {
    "QString": "QString",
    "QVariantList": "QVariantList",
}


def _property_type(prop: QMetaProperty) -> str:
    """Return the QML-tooling spelling of a property's type."""
    name = prop.typeName()
    if not name or prop.metaType().id() == QMetaType.Type.UnknownType.value:
        return "QVariant"
    return _TYPE_ALIASES.get(name, name)


def render() -> str:
    """Build the .qmltypes document for HudController."""
    meta = HudController.staticMetaObject
    type_name = CONTROLLER_TYPE

    out: list[str] = [
        "import QtQuick.tooling 1.2",
        "",
        "// GENERATED by tools/generate_qmltypes.py -- do not edit by hand.",
        "// Describes the Python-side singleton to qmllint and QML tooling.",
        "",
        "Module {",
        "    dependencies: []",
        "    Component {",
        '        file: "javris/controller.py"',
        f'        name: "{HudController.__name__}"',
        '        accessSemantics: "reference"',
        '        prototype: "QObject"',
        f'        exports: ["{QML_MODULE}/{type_name} {QML_MAJOR_VERSION}.{QML_MINOR_VERSION}"]',
        # Must encode the same version as the export, or the tooling reports
        # "Meta object revision and export version differ".
        f"        exportMetaObjectRevisions: [{(QML_MAJOR_VERSION << 8) | QML_MINOR_VERSION}]",
        "        isSingleton: true",
    ]

    # Map each property to the signal that notifies of its change, so QML can
    # tell a live binding from a stale read.
    for index in range(meta.propertyOffset(), meta.propertyCount()):
        prop = meta.property(index)
        parts = [
            f'name: "{prop.name()}"',
            f'type: "{_property_type(prop)}"',
            f'read: "{prop.name()}"',
            f"index: {index - meta.propertyOffset()}",
            "isReadonly: true",
        ]
        if prop.isConstant():
            parts.append("isConstant: true")
        if prop.hasNotifySignal():
            parts.append(f'notify: "{prop.notifySignal().name().data().decode()}"')
        out.append("        Property { " + "; ".join(parts) + " }")

    for index in range(meta.methodOffset(), meta.methodCount()):
        method = meta.method(index)
        name = method.name().data().decode()
        if method.methodType() == QMetaMethod.MethodType.Signal:
            out.append(f'        Signal {{ name: "{name}" }}')
        elif method.methodType() == QMetaMethod.MethodType.Slot:
            parameters = "".join(
                f'\n            Parameter {{ name: "{method.parameterNames()[i].data().decode()}"; '
                f'type: "{method.parameterTypeName(i).data().decode()}" }}'
                for i in range(method.parameterCount())
            )
            return_type = method.typeName() or "void"
            body = f'name: "{name}"; type: "{return_type}"'
            if parameters:
                out.append(f"        Method {{ {body}{parameters}\n        }}")
            else:
                out.append(f"        Method {{ {body} }}")

    out += ["    }", "}", ""]
    return "\n".join(out)


def main() -> int:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(), encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(SRC_ROOT.parent)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
